/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HttpFarmListerExpansion allows custom methods to be added to
// HttpFarmLister.
type HttpFarmListerExpansion interface{}

// HttpFarmNamespaceListerExpansion allows custom methods to be added to
// HttpFarmNamespaceLister.
type HttpFarmNamespaceListerExpansion interface{}

// HttpFarmServerListerExpansion allows custom methods to be added to
// HttpFarmServerLister.
type HttpFarmServerListerExpansion interface{}

// HttpFarmServerNamespaceListerExpansion allows custom methods to be added to
// HttpFarmServerNamespaceLister.
type HttpFarmServerNamespaceListerExpansion interface{}

// HttpFrontendListerExpansion allows custom methods to be added to
// HttpFrontendLister.
type HttpFrontendListerExpansion interface{}

// HttpFrontendNamespaceListerExpansion allows custom methods to be added to
// HttpFrontendNamespaceLister.
type HttpFrontendNamespaceListerExpansion interface{}

// HttpRouteListerExpansion allows custom methods to be added to
// HttpRouteLister.
type HttpRouteListerExpansion interface{}

// HttpRouteNamespaceListerExpansion allows custom methods to be added to
// HttpRouteNamespaceLister.
type HttpRouteNamespaceListerExpansion interface{}

// HttpRouteRuleListerExpansion allows custom methods to be added to
// HttpRouteRuleLister.
type HttpRouteRuleListerExpansion interface{}

// HttpRouteRuleNamespaceListerExpansion allows custom methods to be added to
// HttpRouteRuleNamespaceLister.
type HttpRouteRuleNamespaceListerExpansion interface{}

// IploadbalancingListerExpansion allows custom methods to be added to
// IploadbalancingLister.
type IploadbalancingListerExpansion interface{}

// IploadbalancingNamespaceListerExpansion allows custom methods to be added to
// IploadbalancingNamespaceLister.
type IploadbalancingNamespaceListerExpansion interface{}

// RefreshListerExpansion allows custom methods to be added to
// RefreshLister.
type RefreshListerExpansion interface{}

// RefreshNamespaceListerExpansion allows custom methods to be added to
// RefreshNamespaceLister.
type RefreshNamespaceListerExpansion interface{}

// TcpFarmListerExpansion allows custom methods to be added to
// TcpFarmLister.
type TcpFarmListerExpansion interface{}

// TcpFarmNamespaceListerExpansion allows custom methods to be added to
// TcpFarmNamespaceLister.
type TcpFarmNamespaceListerExpansion interface{}

// TcpFarmServerListerExpansion allows custom methods to be added to
// TcpFarmServerLister.
type TcpFarmServerListerExpansion interface{}

// TcpFarmServerNamespaceListerExpansion allows custom methods to be added to
// TcpFarmServerNamespaceLister.
type TcpFarmServerNamespaceListerExpansion interface{}

// TcpFrontendListerExpansion allows custom methods to be added to
// TcpFrontendLister.
type TcpFrontendListerExpansion interface{}

// TcpFrontendNamespaceListerExpansion allows custom methods to be added to
// TcpFrontendNamespaceLister.
type TcpFrontendNamespaceListerExpansion interface{}

// VrackNetworkListerExpansion allows custom methods to be added to
// VrackNetworkLister.
type VrackNetworkListerExpansion interface{}

// VrackNetworkNamespaceListerExpansion allows custom methods to be added to
// VrackNetworkNamespaceLister.
type VrackNetworkNamespaceListerExpansion interface{}
