/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	mev1alpha1 "kubeform.dev/provider-ovh-api/apis/me/v1alpha1"
	versioned "kubeform.dev/provider-ovh-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-ovh-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-ovh-api/client/listers/me/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InstallationTemplatePartitionSchemeInformer provides access to a shared informer and lister for
// InstallationTemplatePartitionSchemes.
type InstallationTemplatePartitionSchemeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.InstallationTemplatePartitionSchemeLister
}

type installationTemplatePartitionSchemeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInstallationTemplatePartitionSchemeInformer constructs a new informer for InstallationTemplatePartitionScheme type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInstallationTemplatePartitionSchemeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInstallationTemplatePartitionSchemeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInstallationTemplatePartitionSchemeInformer constructs a new informer for InstallationTemplatePartitionScheme type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInstallationTemplatePartitionSchemeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeV1alpha1().InstallationTemplatePartitionSchemes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeV1alpha1().InstallationTemplatePartitionSchemes(namespace).Watch(context.TODO(), options)
			},
		},
		&mev1alpha1.InstallationTemplatePartitionScheme{},
		resyncPeriod,
		indexers,
	)
}

func (f *installationTemplatePartitionSchemeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInstallationTemplatePartitionSchemeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *installationTemplatePartitionSchemeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mev1alpha1.InstallationTemplatePartitionScheme{}, f.defaultInformer)
}

func (f *installationTemplatePartitionSchemeInformer) Lister() v1alpha1.InstallationTemplatePartitionSchemeLister {
	return v1alpha1.NewInstallationTemplatePartitionSchemeLister(f.Informer().GetIndexer())
}
