/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// ProjectNamespaceListerExpansion allows custom methods to be added to
// ProjectNamespaceLister.
type ProjectNamespaceListerExpansion interface{}

// ProjectContainerregistryListerExpansion allows custom methods to be added to
// ProjectContainerregistryLister.
type ProjectContainerregistryListerExpansion interface{}

// ProjectContainerregistryNamespaceListerExpansion allows custom methods to be added to
// ProjectContainerregistryNamespaceLister.
type ProjectContainerregistryNamespaceListerExpansion interface{}

// ProjectContainerregistryUserListerExpansion allows custom methods to be added to
// ProjectContainerregistryUserLister.
type ProjectContainerregistryUserListerExpansion interface{}

// ProjectContainerregistryUserNamespaceListerExpansion allows custom methods to be added to
// ProjectContainerregistryUserNamespaceLister.
type ProjectContainerregistryUserNamespaceListerExpansion interface{}

// ProjectKubeListerExpansion allows custom methods to be added to
// ProjectKubeLister.
type ProjectKubeListerExpansion interface{}

// ProjectKubeNamespaceListerExpansion allows custom methods to be added to
// ProjectKubeNamespaceLister.
type ProjectKubeNamespaceListerExpansion interface{}

// ProjectKubeNodepoolListerExpansion allows custom methods to be added to
// ProjectKubeNodepoolLister.
type ProjectKubeNodepoolListerExpansion interface{}

// ProjectKubeNodepoolNamespaceListerExpansion allows custom methods to be added to
// ProjectKubeNodepoolNamespaceLister.
type ProjectKubeNodepoolNamespaceListerExpansion interface{}

// ProjectNetworkPrivateListerExpansion allows custom methods to be added to
// ProjectNetworkPrivateLister.
type ProjectNetworkPrivateListerExpansion interface{}

// ProjectNetworkPrivateNamespaceListerExpansion allows custom methods to be added to
// ProjectNetworkPrivateNamespaceLister.
type ProjectNetworkPrivateNamespaceListerExpansion interface{}

// ProjectNetworkPrivateSubnetListerExpansion allows custom methods to be added to
// ProjectNetworkPrivateSubnetLister.
type ProjectNetworkPrivateSubnetListerExpansion interface{}

// ProjectNetworkPrivateSubnetNamespaceListerExpansion allows custom methods to be added to
// ProjectNetworkPrivateSubnetNamespaceLister.
type ProjectNetworkPrivateSubnetNamespaceListerExpansion interface{}

// ProjectUserListerExpansion allows custom methods to be added to
// ProjectUserLister.
type ProjectUserListerExpansion interface{}

// ProjectUserNamespaceListerExpansion allows custom methods to be added to
// ProjectUserNamespaceLister.
type ProjectUserNamespaceListerExpansion interface{}
