/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-ovh-api/apis/cloud/v1alpha1"
	"kubeform.dev/provider-ovh-api/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type CloudV1alpha1Interface interface {
	RESTClient() rest.Interface
	ProjectsGetter
	ProjectContainerregistriesGetter
	ProjectContainerregistryUsersGetter
	ProjectKubesGetter
	ProjectKubeNodepoolsGetter
	ProjectNetworkPrivatesGetter
	ProjectNetworkPrivateSubnetsGetter
	ProjectUsersGetter
}

// CloudV1alpha1Client is used to interact with features provided by the cloud.ovh.kubeform.com group.
type CloudV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CloudV1alpha1Client) Projects(namespace string) ProjectInterface {
	return newProjects(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectContainerregistries(namespace string) ProjectContainerregistryInterface {
	return newProjectContainerregistries(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectContainerregistryUsers(namespace string) ProjectContainerregistryUserInterface {
	return newProjectContainerregistryUsers(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectKubes(namespace string) ProjectKubeInterface {
	return newProjectKubes(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectKubeNodepools(namespace string) ProjectKubeNodepoolInterface {
	return newProjectKubeNodepools(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectNetworkPrivates(namespace string) ProjectNetworkPrivateInterface {
	return newProjectNetworkPrivates(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectNetworkPrivateSubnets(namespace string) ProjectNetworkPrivateSubnetInterface {
	return newProjectNetworkPrivateSubnets(c, namespace)
}

func (c *CloudV1alpha1Client) ProjectUsers(namespace string) ProjectUserInterface {
	return newProjectUsers(c, namespace)
}

// NewForConfig creates a new CloudV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CloudV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CloudV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CloudV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CloudV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CloudV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CloudV1alpha1Client {
	return &CloudV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CloudV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
