/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/cloud/v1alpha1"
	scheme "kubeform.dev/provider-ovh-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProjectNetworkPrivatesGetter has a method to return a ProjectNetworkPrivateInterface.
// A group's client should implement this interface.
type ProjectNetworkPrivatesGetter interface {
	ProjectNetworkPrivates(namespace string) ProjectNetworkPrivateInterface
}

// ProjectNetworkPrivateInterface has methods to work with ProjectNetworkPrivate resources.
type ProjectNetworkPrivateInterface interface {
	Create(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.CreateOptions) (*v1alpha1.ProjectNetworkPrivate, error)
	Update(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (*v1alpha1.ProjectNetworkPrivate, error)
	UpdateStatus(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (*v1alpha1.ProjectNetworkPrivate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ProjectNetworkPrivate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ProjectNetworkPrivateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectNetworkPrivate, err error)
	ProjectNetworkPrivateExpansion
}

// projectNetworkPrivates implements ProjectNetworkPrivateInterface
type projectNetworkPrivates struct {
	client rest.Interface
	ns     string
}

// newProjectNetworkPrivates returns a ProjectNetworkPrivates
func newProjectNetworkPrivates(c *CloudV1alpha1Client, namespace string) *projectNetworkPrivates {
	return &projectNetworkPrivates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the projectNetworkPrivate, and returns the corresponding projectNetworkPrivate object, and an error if there is any.
func (c *projectNetworkPrivates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	result = &v1alpha1.ProjectNetworkPrivate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProjectNetworkPrivates that match those selectors.
func (c *projectNetworkPrivates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectNetworkPrivateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ProjectNetworkPrivateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested projectNetworkPrivates.
func (c *projectNetworkPrivates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a projectNetworkPrivate and creates it.  Returns the server's representation of the projectNetworkPrivate, and an error, if there is any.
func (c *projectNetworkPrivates) Create(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.CreateOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	result = &v1alpha1.ProjectNetworkPrivate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectNetworkPrivate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a projectNetworkPrivate and updates it. Returns the server's representation of the projectNetworkPrivate, and an error, if there is any.
func (c *projectNetworkPrivates) Update(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	result = &v1alpha1.ProjectNetworkPrivate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		Name(projectNetworkPrivate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectNetworkPrivate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *projectNetworkPrivates) UpdateStatus(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	result = &v1alpha1.ProjectNetworkPrivate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		Name(projectNetworkPrivate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(projectNetworkPrivate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the projectNetworkPrivate and deletes it. Returns an error if one occurs.
func (c *projectNetworkPrivates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *projectNetworkPrivates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched projectNetworkPrivate.
func (c *projectNetworkPrivates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	result = &v1alpha1.ProjectNetworkPrivate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("projectnetworkprivates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
