/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectNetworkPrivates implements ProjectNetworkPrivateInterface
type FakeProjectNetworkPrivates struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var projectnetworkprivatesResource = schema.GroupVersionResource{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Resource: "projectnetworkprivates"}

var projectnetworkprivatesKind = schema.GroupVersionKind{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Kind: "ProjectNetworkPrivate"}

// Get takes name of the projectNetworkPrivate, and returns the corresponding projectNetworkPrivate object, and an error if there is any.
func (c *FakeProjectNetworkPrivates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectnetworkprivatesResource, c.ns, name), &v1alpha1.ProjectNetworkPrivate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectNetworkPrivate), err
}

// List takes label and field selectors, and returns the list of ProjectNetworkPrivates that match those selectors.
func (c *FakeProjectNetworkPrivates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectNetworkPrivateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectnetworkprivatesResource, projectnetworkprivatesKind, c.ns, opts), &v1alpha1.ProjectNetworkPrivateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectNetworkPrivateList{ListMeta: obj.(*v1alpha1.ProjectNetworkPrivateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectNetworkPrivateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectNetworkPrivates.
func (c *FakeProjectNetworkPrivates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectnetworkprivatesResource, c.ns, opts))

}

// Create takes the representation of a projectNetworkPrivate and creates it.  Returns the server's representation of the projectNetworkPrivate, and an error, if there is any.
func (c *FakeProjectNetworkPrivates) Create(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.CreateOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectnetworkprivatesResource, c.ns, projectNetworkPrivate), &v1alpha1.ProjectNetworkPrivate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectNetworkPrivate), err
}

// Update takes the representation of a projectNetworkPrivate and updates it. Returns the server's representation of the projectNetworkPrivate, and an error, if there is any.
func (c *FakeProjectNetworkPrivates) Update(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectnetworkprivatesResource, c.ns, projectNetworkPrivate), &v1alpha1.ProjectNetworkPrivate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectNetworkPrivate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectNetworkPrivates) UpdateStatus(ctx context.Context, projectNetworkPrivate *v1alpha1.ProjectNetworkPrivate, opts v1.UpdateOptions) (*v1alpha1.ProjectNetworkPrivate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectnetworkprivatesResource, "status", c.ns, projectNetworkPrivate), &v1alpha1.ProjectNetworkPrivate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectNetworkPrivate), err
}

// Delete takes name of the projectNetworkPrivate and deletes it. Returns an error if one occurs.
func (c *FakeProjectNetworkPrivates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectnetworkprivatesResource, c.ns, name), &v1alpha1.ProjectNetworkPrivate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectNetworkPrivates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectnetworkprivatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectNetworkPrivateList{})
	return err
}

// Patch applies the patch and returns the patched projectNetworkPrivate.
func (c *FakeProjectNetworkPrivates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectNetworkPrivate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectnetworkprivatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectNetworkPrivate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectNetworkPrivate), err
}
