/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectContainerregistries implements ProjectContainerregistryInterface
type FakeProjectContainerregistries struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var projectcontainerregistriesResource = schema.GroupVersionResource{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Resource: "projectcontainerregistries"}

var projectcontainerregistriesKind = schema.GroupVersionKind{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Kind: "ProjectContainerregistry"}

// Get takes name of the projectContainerregistry, and returns the corresponding projectContainerregistry object, and an error if there is any.
func (c *FakeProjectContainerregistries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectContainerregistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectcontainerregistriesResource, c.ns, name), &v1alpha1.ProjectContainerregistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectContainerregistry), err
}

// List takes label and field selectors, and returns the list of ProjectContainerregistries that match those selectors.
func (c *FakeProjectContainerregistries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectContainerregistryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectcontainerregistriesResource, projectcontainerregistriesKind, c.ns, opts), &v1alpha1.ProjectContainerregistryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectContainerregistryList{ListMeta: obj.(*v1alpha1.ProjectContainerregistryList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectContainerregistryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectContainerregistries.
func (c *FakeProjectContainerregistries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectcontainerregistriesResource, c.ns, opts))

}

// Create takes the representation of a projectContainerregistry and creates it.  Returns the server's representation of the projectContainerregistry, and an error, if there is any.
func (c *FakeProjectContainerregistries) Create(ctx context.Context, projectContainerregistry *v1alpha1.ProjectContainerregistry, opts v1.CreateOptions) (result *v1alpha1.ProjectContainerregistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectcontainerregistriesResource, c.ns, projectContainerregistry), &v1alpha1.ProjectContainerregistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectContainerregistry), err
}

// Update takes the representation of a projectContainerregistry and updates it. Returns the server's representation of the projectContainerregistry, and an error, if there is any.
func (c *FakeProjectContainerregistries) Update(ctx context.Context, projectContainerregistry *v1alpha1.ProjectContainerregistry, opts v1.UpdateOptions) (result *v1alpha1.ProjectContainerregistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectcontainerregistriesResource, c.ns, projectContainerregistry), &v1alpha1.ProjectContainerregistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectContainerregistry), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectContainerregistries) UpdateStatus(ctx context.Context, projectContainerregistry *v1alpha1.ProjectContainerregistry, opts v1.UpdateOptions) (*v1alpha1.ProjectContainerregistry, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectcontainerregistriesResource, "status", c.ns, projectContainerregistry), &v1alpha1.ProjectContainerregistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectContainerregistry), err
}

// Delete takes name of the projectContainerregistry and deletes it. Returns an error if one occurs.
func (c *FakeProjectContainerregistries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectcontainerregistriesResource, c.ns, name), &v1alpha1.ProjectContainerregistry{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectContainerregistries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectcontainerregistriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectContainerregistryList{})
	return err
}

// Patch applies the patch and returns the patched projectContainerregistry.
func (c *FakeProjectContainerregistries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectContainerregistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectcontainerregistriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectContainerregistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectContainerregistry), err
}
