/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProjectKubeNodepools implements ProjectKubeNodepoolInterface
type FakeProjectKubeNodepools struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var projectkubenodepoolsResource = schema.GroupVersionResource{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Resource: "projectkubenodepools"}

var projectkubenodepoolsKind = schema.GroupVersionKind{Group: "cloud.ovh.kubeform.com", Version: "v1alpha1", Kind: "ProjectKubeNodepool"}

// Get takes name of the projectKubeNodepool, and returns the corresponding projectKubeNodepool object, and an error if there is any.
func (c *FakeProjectKubeNodepools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProjectKubeNodepool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(projectkubenodepoolsResource, c.ns, name), &v1alpha1.ProjectKubeNodepool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectKubeNodepool), err
}

// List takes label and field selectors, and returns the list of ProjectKubeNodepools that match those selectors.
func (c *FakeProjectKubeNodepools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProjectKubeNodepoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(projectkubenodepoolsResource, projectkubenodepoolsKind, c.ns, opts), &v1alpha1.ProjectKubeNodepoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProjectKubeNodepoolList{ListMeta: obj.(*v1alpha1.ProjectKubeNodepoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProjectKubeNodepoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectKubeNodepools.
func (c *FakeProjectKubeNodepools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(projectkubenodepoolsResource, c.ns, opts))

}

// Create takes the representation of a projectKubeNodepool and creates it.  Returns the server's representation of the projectKubeNodepool, and an error, if there is any.
func (c *FakeProjectKubeNodepools) Create(ctx context.Context, projectKubeNodepool *v1alpha1.ProjectKubeNodepool, opts v1.CreateOptions) (result *v1alpha1.ProjectKubeNodepool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(projectkubenodepoolsResource, c.ns, projectKubeNodepool), &v1alpha1.ProjectKubeNodepool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectKubeNodepool), err
}

// Update takes the representation of a projectKubeNodepool and updates it. Returns the server's representation of the projectKubeNodepool, and an error, if there is any.
func (c *FakeProjectKubeNodepools) Update(ctx context.Context, projectKubeNodepool *v1alpha1.ProjectKubeNodepool, opts v1.UpdateOptions) (result *v1alpha1.ProjectKubeNodepool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(projectkubenodepoolsResource, c.ns, projectKubeNodepool), &v1alpha1.ProjectKubeNodepool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectKubeNodepool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectKubeNodepools) UpdateStatus(ctx context.Context, projectKubeNodepool *v1alpha1.ProjectKubeNodepool, opts v1.UpdateOptions) (*v1alpha1.ProjectKubeNodepool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(projectkubenodepoolsResource, "status", c.ns, projectKubeNodepool), &v1alpha1.ProjectKubeNodepool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectKubeNodepool), err
}

// Delete takes name of the projectKubeNodepool and deletes it. Returns an error if one occurs.
func (c *FakeProjectKubeNodepools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(projectkubenodepoolsResource, c.ns, name), &v1alpha1.ProjectKubeNodepool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectKubeNodepools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(projectkubenodepoolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProjectKubeNodepoolList{})
	return err
}

// Patch applies the patch and returns the patched projectKubeNodepool.
func (c *FakeProjectKubeNodepools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProjectKubeNodepool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(projectkubenodepoolsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProjectKubeNodepool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProjectKubeNodepool), err
}
