/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CloudprojectListerExpansion allows custom methods to be added to
// CloudprojectLister.
type CloudprojectListerExpansion interface{}

// CloudprojectNamespaceListerExpansion allows custom methods to be added to
// CloudprojectNamespaceLister.
type CloudprojectNamespaceListerExpansion interface{}

// DedicatedServerListerExpansion allows custom methods to be added to
// DedicatedServerLister.
type DedicatedServerListerExpansion interface{}

// DedicatedServerNamespaceListerExpansion allows custom methods to be added to
// DedicatedServerNamespaceLister.
type DedicatedServerNamespaceListerExpansion interface{}

// DedicatedServerInterfaceListerExpansion allows custom methods to be added to
// DedicatedServerInterfaceLister.
type DedicatedServerInterfaceListerExpansion interface{}

// DedicatedServerInterfaceNamespaceListerExpansion allows custom methods to be added to
// DedicatedServerInterfaceNamespaceLister.
type DedicatedServerInterfaceNamespaceListerExpansion interface{}

// IpListerExpansion allows custom methods to be added to
// IpLister.
type IpListerExpansion interface{}

// IpNamespaceListerExpansion allows custom methods to be added to
// IpNamespaceLister.
type IpNamespaceListerExpansion interface{}

// IploadbalancingListerExpansion allows custom methods to be added to
// IploadbalancingLister.
type IploadbalancingListerExpansion interface{}

// IploadbalancingNamespaceListerExpansion allows custom methods to be added to
// IploadbalancingNamespaceLister.
type IploadbalancingNamespaceListerExpansion interface{}

// VrackListerExpansion allows custom methods to be added to
// VrackLister.
type VrackListerExpansion interface{}

// VrackNamespaceListerExpansion allows custom methods to be added to
// VrackNamespaceLister.
type VrackNamespaceListerExpansion interface{}
