/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	vrackv1alpha1 "kubeform.dev/provider-ovh-api/apis/vrack/v1alpha1"
	versioned "kubeform.dev/provider-ovh-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-ovh-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-ovh-api/client/listers/vrack/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DedicatedServerInterfaceInformer provides access to a shared informer and lister for
// DedicatedServerInterfaces.
type DedicatedServerInterfaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DedicatedServerInterfaceLister
}

type dedicatedServerInterfaceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDedicatedServerInterfaceInformer constructs a new informer for DedicatedServerInterface type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDedicatedServerInterfaceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDedicatedServerInterfaceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDedicatedServerInterfaceInformer constructs a new informer for DedicatedServerInterface type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDedicatedServerInterfaceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VrackV1alpha1().DedicatedServerInterfaces(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VrackV1alpha1().DedicatedServerInterfaces(namespace).Watch(context.TODO(), options)
			},
		},
		&vrackv1alpha1.DedicatedServerInterface{},
		resyncPeriod,
		indexers,
	)
}

func (f *dedicatedServerInterfaceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDedicatedServerInterfaceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dedicatedServerInterfaceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vrackv1alpha1.DedicatedServerInterface{}, f.defaultInformer)
}

func (f *dedicatedServerInterfaceInformer) Lister() v1alpha1.DedicatedServerInterfaceLister {
	return v1alpha1.NewDedicatedServerInterfaceLister(f.Informer().GetIndexer())
}
