/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CephACLListerExpansion allows custom methods to be added to
// CephACLLister.
type CephACLListerExpansion interface{}

// CephACLNamespaceListerExpansion allows custom methods to be added to
// CephACLNamespaceLister.
type CephACLNamespaceListerExpansion interface{}

// ServerInstallTaskListerExpansion allows custom methods to be added to
// ServerInstallTaskLister.
type ServerInstallTaskListerExpansion interface{}

// ServerInstallTaskNamespaceListerExpansion allows custom methods to be added to
// ServerInstallTaskNamespaceLister.
type ServerInstallTaskNamespaceListerExpansion interface{}

// ServerRebootTaskListerExpansion allows custom methods to be added to
// ServerRebootTaskLister.
type ServerRebootTaskListerExpansion interface{}

// ServerRebootTaskNamespaceListerExpansion allows custom methods to be added to
// ServerRebootTaskNamespaceLister.
type ServerRebootTaskNamespaceListerExpansion interface{}

// ServerUpdateListerExpansion allows custom methods to be added to
// ServerUpdateLister.
type ServerUpdateListerExpansion interface{}

// ServerUpdateNamespaceListerExpansion allows custom methods to be added to
// ServerUpdateNamespaceLister.
type ServerUpdateNamespaceListerExpansion interface{}
