/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/me/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIdentityUsers implements IdentityUserInterface
type FakeIdentityUsers struct {
	Fake *FakeMeV1alpha1
	ns   string
}

var identityusersResource = schema.GroupVersionResource{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Resource: "identityusers"}

var identityusersKind = schema.GroupVersionKind{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Kind: "IdentityUser"}

// Get takes name of the identityUser, and returns the corresponding identityUser object, and an error if there is any.
func (c *FakeIdentityUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IdentityUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(identityusersResource, c.ns, name), &v1alpha1.IdentityUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityUser), err
}

// List takes label and field selectors, and returns the list of IdentityUsers that match those selectors.
func (c *FakeIdentityUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IdentityUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(identityusersResource, identityusersKind, c.ns, opts), &v1alpha1.IdentityUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IdentityUserList{ListMeta: obj.(*v1alpha1.IdentityUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.IdentityUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested identityUsers.
func (c *FakeIdentityUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(identityusersResource, c.ns, opts))

}

// Create takes the representation of a identityUser and creates it.  Returns the server's representation of the identityUser, and an error, if there is any.
func (c *FakeIdentityUsers) Create(ctx context.Context, identityUser *v1alpha1.IdentityUser, opts v1.CreateOptions) (result *v1alpha1.IdentityUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(identityusersResource, c.ns, identityUser), &v1alpha1.IdentityUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityUser), err
}

// Update takes the representation of a identityUser and updates it. Returns the server's representation of the identityUser, and an error, if there is any.
func (c *FakeIdentityUsers) Update(ctx context.Context, identityUser *v1alpha1.IdentityUser, opts v1.UpdateOptions) (result *v1alpha1.IdentityUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(identityusersResource, c.ns, identityUser), &v1alpha1.IdentityUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIdentityUsers) UpdateStatus(ctx context.Context, identityUser *v1alpha1.IdentityUser, opts v1.UpdateOptions) (*v1alpha1.IdentityUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(identityusersResource, "status", c.ns, identityUser), &v1alpha1.IdentityUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityUser), err
}

// Delete takes name of the identityUser and deletes it. Returns an error if one occurs.
func (c *FakeIdentityUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(identityusersResource, c.ns, name), &v1alpha1.IdentityUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIdentityUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(identityusersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IdentityUserList{})
	return err
}

// Patch applies the patch and returns the patched identityUser.
func (c *FakeIdentityUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IdentityUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(identityusersResource, c.ns, name, pt, data, subresources...), &v1alpha1.IdentityUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IdentityUser), err
}
