/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/me/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInstallationTemplates implements InstallationTemplateInterface
type FakeInstallationTemplates struct {
	Fake *FakeMeV1alpha1
	ns   string
}

var installationtemplatesResource = schema.GroupVersionResource{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Resource: "installationtemplates"}

var installationtemplatesKind = schema.GroupVersionKind{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Kind: "InstallationTemplate"}

// Get takes name of the installationTemplate, and returns the corresponding installationTemplate object, and an error if there is any.
func (c *FakeInstallationTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InstallationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(installationtemplatesResource, c.ns, name), &v1alpha1.InstallationTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstallationTemplate), err
}

// List takes label and field selectors, and returns the list of InstallationTemplates that match those selectors.
func (c *FakeInstallationTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InstallationTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(installationtemplatesResource, installationtemplatesKind, c.ns, opts), &v1alpha1.InstallationTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InstallationTemplateList{ListMeta: obj.(*v1alpha1.InstallationTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.InstallationTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested installationTemplates.
func (c *FakeInstallationTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(installationtemplatesResource, c.ns, opts))

}

// Create takes the representation of a installationTemplate and creates it.  Returns the server's representation of the installationTemplate, and an error, if there is any.
func (c *FakeInstallationTemplates) Create(ctx context.Context, installationTemplate *v1alpha1.InstallationTemplate, opts v1.CreateOptions) (result *v1alpha1.InstallationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(installationtemplatesResource, c.ns, installationTemplate), &v1alpha1.InstallationTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstallationTemplate), err
}

// Update takes the representation of a installationTemplate and updates it. Returns the server's representation of the installationTemplate, and an error, if there is any.
func (c *FakeInstallationTemplates) Update(ctx context.Context, installationTemplate *v1alpha1.InstallationTemplate, opts v1.UpdateOptions) (result *v1alpha1.InstallationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(installationtemplatesResource, c.ns, installationTemplate), &v1alpha1.InstallationTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstallationTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInstallationTemplates) UpdateStatus(ctx context.Context, installationTemplate *v1alpha1.InstallationTemplate, opts v1.UpdateOptions) (*v1alpha1.InstallationTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(installationtemplatesResource, "status", c.ns, installationTemplate), &v1alpha1.InstallationTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstallationTemplate), err
}

// Delete takes name of the installationTemplate and deletes it. Returns an error if one occurs.
func (c *FakeInstallationTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(installationtemplatesResource, c.ns, name), &v1alpha1.InstallationTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInstallationTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(installationtemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InstallationTemplateList{})
	return err
}

// Patch applies the patch and returns the patched installationTemplate.
func (c *FakeInstallationTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InstallationTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(installationtemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.InstallationTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InstallationTemplate), err
}
