/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/me/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIpxeScripts implements IpxeScriptInterface
type FakeIpxeScripts struct {
	Fake *FakeMeV1alpha1
	ns   string
}

var ipxescriptsResource = schema.GroupVersionResource{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Resource: "ipxescripts"}

var ipxescriptsKind = schema.GroupVersionKind{Group: "me.ovh.kubeform.com", Version: "v1alpha1", Kind: "IpxeScript"}

// Get takes name of the ipxeScript, and returns the corresponding ipxeScript object, and an error if there is any.
func (c *FakeIpxeScripts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IpxeScript, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipxescriptsResource, c.ns, name), &v1alpha1.IpxeScript{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IpxeScript), err
}

// List takes label and field selectors, and returns the list of IpxeScripts that match those selectors.
func (c *FakeIpxeScripts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IpxeScriptList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipxescriptsResource, ipxescriptsKind, c.ns, opts), &v1alpha1.IpxeScriptList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IpxeScriptList{ListMeta: obj.(*v1alpha1.IpxeScriptList).ListMeta}
	for _, item := range obj.(*v1alpha1.IpxeScriptList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ipxeScripts.
func (c *FakeIpxeScripts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipxescriptsResource, c.ns, opts))

}

// Create takes the representation of a ipxeScript and creates it.  Returns the server's representation of the ipxeScript, and an error, if there is any.
func (c *FakeIpxeScripts) Create(ctx context.Context, ipxeScript *v1alpha1.IpxeScript, opts v1.CreateOptions) (result *v1alpha1.IpxeScript, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipxescriptsResource, c.ns, ipxeScript), &v1alpha1.IpxeScript{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IpxeScript), err
}

// Update takes the representation of a ipxeScript and updates it. Returns the server's representation of the ipxeScript, and an error, if there is any.
func (c *FakeIpxeScripts) Update(ctx context.Context, ipxeScript *v1alpha1.IpxeScript, opts v1.UpdateOptions) (result *v1alpha1.IpxeScript, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipxescriptsResource, c.ns, ipxeScript), &v1alpha1.IpxeScript{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IpxeScript), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIpxeScripts) UpdateStatus(ctx context.Context, ipxeScript *v1alpha1.IpxeScript, opts v1.UpdateOptions) (*v1alpha1.IpxeScript, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipxescriptsResource, "status", c.ns, ipxeScript), &v1alpha1.IpxeScript{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IpxeScript), err
}

// Delete takes name of the ipxeScript and deletes it. Returns an error if one occurs.
func (c *FakeIpxeScripts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipxescriptsResource, c.ns, name), &v1alpha1.IpxeScript{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIpxeScripts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipxescriptsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IpxeScriptList{})
	return err
}

// Patch applies the patch and returns the patched ipxeScript.
func (c *FakeIpxeScripts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IpxeScript, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipxescriptsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IpxeScript{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IpxeScript), err
}
