apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ovh.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: projectcontainerregistries.cloud.ovh.kubeform.com
spec:
  group: cloud.ovh.kubeform.com
  names:
    kind: ProjectContainerregistry
    listKind: ProjectContainerregistryList
    plural: projectcontainerregistries
    singular: projectcontainerregistry
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  createdAt:
                    description: Registry creation date
                    type: string
                  id:
                    type: string
                  name:
                    description: Registry name
                    type: string
                  plan:
                    description: Plan of the registry
                    items:
                      properties:
                        ID:
                          description: Plan ID
                          type: string
                        code:
                          description: Plan code from catalog
                          type: string
                        createdAt:
                          description: Plan creation date
                          type: string
                        features:
                          description: Features of the plan
                          items:
                            properties:
                              vulnerability:
                                description: Vulnerability scanning
                                type: boolean
                            type: object
                          type: array
                        name:
                          description: Plan name
                          type: string
                        registryLimits:
                          description: Container registry limits
                          items:
                            properties:
                              imageStorage:
                                description: Docker image storage limits in bytes
                                format: int64
                                type: integer
                              parallelRequest:
                                description: Parallel requests on Docker image API
                                  (/v2 Docker registry API)
                                format: int64
                                type: integer
                            type: object
                          type: array
                        updatedAt:
                          description: Plan last update date
                          type: string
                      type: object
                    type: array
                  planID:
                    description: Plan ID of the registry.
                    type: string
                  projectID:
                    description: Project ID of your registry
                    type: string
                  region:
                    description: Region of the registry.
                    type: string
                  serviceName:
                    type: string
                  size:
                    description: Current size of the registry (bytes)
                    format: int64
                    type: integer
                  status:
                    description: Registry status
                    type: string
                  updatedAt:
                    description: Registry last update date
                    type: string
                  url:
                    description: Access url of the registry
                    type: string
                  version:
                    description: Version of your registry
                    type: string
                required:
                - name
                - region
                - serviceName
                type: object
              state:
                properties:
                  createdAt:
                    description: Registry creation date
                    type: string
                  id:
                    type: string
                  name:
                    description: Registry name
                    type: string
                  plan:
                    description: Plan of the registry
                    items:
                      properties:
                        ID:
                          description: Plan ID
                          type: string
                        code:
                          description: Plan code from catalog
                          type: string
                        createdAt:
                          description: Plan creation date
                          type: string
                        features:
                          description: Features of the plan
                          items:
                            properties:
                              vulnerability:
                                description: Vulnerability scanning
                                type: boolean
                            type: object
                          type: array
                        name:
                          description: Plan name
                          type: string
                        registryLimits:
                          description: Container registry limits
                          items:
                            properties:
                              imageStorage:
                                description: Docker image storage limits in bytes
                                format: int64
                                type: integer
                              parallelRequest:
                                description: Parallel requests on Docker image API
                                  (/v2 Docker registry API)
                                format: int64
                                type: integer
                            type: object
                          type: array
                        updatedAt:
                          description: Plan last update date
                          type: string
                      type: object
                    type: array
                  planID:
                    description: Plan ID of the registry.
                    type: string
                  projectID:
                    description: Project ID of your registry
                    type: string
                  region:
                    description: Region of the registry.
                    type: string
                  serviceName:
                    type: string
                  size:
                    description: Current size of the registry (bytes)
                    format: int64
                    type: integer
                  status:
                    description: Registry status
                    type: string
                  updatedAt:
                    description: Registry last update date
                    type: string
                  url:
                    description: Access url of the registry
                    type: string
                  version:
                    description: Version of your registry
                    type: string
                required:
                - name
                - region
                - serviceName
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
