apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ovh.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: logsinputs.dbaas.ovh.kubeform.com
spec:
  group: dbaas.ovh.kubeform.com
  names:
    kind: LogsInput
    listKind: LogsInputList
    plural: logsinputs
    singular: logsinput
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  allowedNetworks:
                    description: IP blocks
                    items:
                      type: string
                    type: array
                  configuration:
                    description: Input configuration
                    properties:
                      flowgger:
                        description: Flowgger configuration
                        properties:
                          logFormat:
                            description: Type of format to decode
                            type: string
                          logFraming:
                            description: Indicates how messages are delimited
                            type: string
                        required:
                        - logFormat
                        - logFraming
                        type: object
                      logstash:
                        description: Logstash configuration
                        properties:
                          filterSection:
                            description: The filter section of logstash.conf
                            type: string
                          inputSection:
                            description: The filter section of logstash.conf
                            type: string
                          patternSection:
                            description: The list of customs Grok patterns
                            type: string
                        required:
                        - inputSection
                        type: object
                    type: object
                  createdAt:
                    description: Input creation
                    type: string
                  description:
                    description: Input description
                    type: string
                  engineID:
                    description: Input engine ID
                    type: string
                  exposedPort:
                    description: Port
                    type: string
                  hostname:
                    description: Hostname
                    type: string
                  id:
                    type: string
                  inputID:
                    description: Input ID
                    type: string
                  isRestartRequired:
                    description: Indicate if input need to be restarted
                    type: boolean
                  nbInstance:
                    description: Number of instance running
                    format: int64
                    type: integer
                  publicAddress:
                    description: Input IP address
                    type: string
                  serviceName:
                    type: string
                  status:
                    description: 'init: configuration required, pending: ready to
                      start, running: available'
                    type: string
                  streamID:
                    description: Associated Graylog stream
                    type: string
                  title:
                    description: Input title
                    type: string
                  updatedAt:
                    description: Input last update
                    type: string
                required:
                - configuration
                - description
                - engineID
                - serviceName
                - streamID
                - title
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  allowedNetworks:
                    description: IP blocks
                    items:
                      type: string
                    type: array
                  configuration:
                    description: Input configuration
                    properties:
                      flowgger:
                        description: Flowgger configuration
                        properties:
                          logFormat:
                            description: Type of format to decode
                            type: string
                          logFraming:
                            description: Indicates how messages are delimited
                            type: string
                        required:
                        - logFormat
                        - logFraming
                        type: object
                      logstash:
                        description: Logstash configuration
                        properties:
                          filterSection:
                            description: The filter section of logstash.conf
                            type: string
                          inputSection:
                            description: The filter section of logstash.conf
                            type: string
                          patternSection:
                            description: The list of customs Grok patterns
                            type: string
                        required:
                        - inputSection
                        type: object
                    type: object
                  createdAt:
                    description: Input creation
                    type: string
                  description:
                    description: Input description
                    type: string
                  engineID:
                    description: Input engine ID
                    type: string
                  exposedPort:
                    description: Port
                    type: string
                  hostname:
                    description: Hostname
                    type: string
                  id:
                    type: string
                  inputID:
                    description: Input ID
                    type: string
                  isRestartRequired:
                    description: Indicate if input need to be restarted
                    type: boolean
                  nbInstance:
                    description: Number of instance running
                    format: int64
                    type: integer
                  publicAddress:
                    description: Input IP address
                    type: string
                  serviceName:
                    type: string
                  status:
                    description: 'init: configuration required, pending: ready to
                      start, running: available'
                    type: string
                  streamID:
                    description: Associated Graylog stream
                    type: string
                  title:
                    description: Input title
                    type: string
                  updatedAt:
                    description: Input last update
                    type: string
                required:
                - configuration
                - description
                - engineID
                - serviceName
                - streamID
                - title
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
