apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ovh.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: logsoutputgraylogstreams.dbaas.ovh.kubeform.com
spec:
  group: dbaas.ovh.kubeform.com
  names:
    kind: LogsOutputGraylogStream
    listKind: LogsOutputGraylogStreamList
    plural: logsoutputgraylogstreams
    singular: logsoutputgraylogstream
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  canAlert:
                    description: Indicates if the current user can create alert on
                      the stream
                    type: boolean
                  coldStorageCompression:
                    description: Cold storage compression method
                    type: string
                  coldStorageContent:
                    description: ColdStorage content
                    type: string
                  coldStorageEnabled:
                    description: Is Cold storage enabled?
                    type: boolean
                  coldStorageNotifyEnabled:
                    description: Notify on new Cold storage archive
                    type: boolean
                  coldStorageRetention:
                    description: Cold storage retention in year
                    format: int64
                    type: integer
                  coldStorageTarget:
                    description: ColdStorage destination
                    type: string
                  createdAt:
                    description: Stream creation
                    type: string
                  description:
                    description: Stream description
                    type: string
                  id:
                    type: string
                  indexingEnabled:
                    description: Enable ES indexing
                    type: boolean
                  indexingMaxSize:
                    description: Maximum indexing size (in GB)
                    format: int64
                    type: integer
                  indexingNotifyEnabled:
                    description: If set, notify when size is near 80, 90 or 100 %
                      of the maximum configured setting
                    type: boolean
                  isEditable:
                    description: Indicates if you are allowed to edit entry
                    type: boolean
                  isShareable:
                    description: Indicates if you are allowed to share entry
                    type: boolean
                  nbAlertCondition:
                    description: Number of alert condition
                    format: int64
                    type: integer
                  nbArchive:
                    description: Number of coldstored archives
                    format: int64
                    type: integer
                  parentStreamID:
                    description: Parent stream ID
                    type: string
                  pauseIndexingOnMaxSize:
                    description: If set, pause indexing when maximum size is reach
                    type: boolean
                  retentionID:
                    description: Retention ID
                    type: string
                  serviceName:
                    description: The service name
                    type: string
                  streamID:
                    description: Stream ID
                    type: string
                  title:
                    description: Stream description
                    type: string
                  updatedAt:
                    description: Stream last update
                    type: string
                  webSocketEnabled:
                    description: Enable Websocket
                    type: boolean
                required:
                - description
                - serviceName
                - title
                type: object
              state:
                properties:
                  canAlert:
                    description: Indicates if the current user can create alert on
                      the stream
                    type: boolean
                  coldStorageCompression:
                    description: Cold storage compression method
                    type: string
                  coldStorageContent:
                    description: ColdStorage content
                    type: string
                  coldStorageEnabled:
                    description: Is Cold storage enabled?
                    type: boolean
                  coldStorageNotifyEnabled:
                    description: Notify on new Cold storage archive
                    type: boolean
                  coldStorageRetention:
                    description: Cold storage retention in year
                    format: int64
                    type: integer
                  coldStorageTarget:
                    description: ColdStorage destination
                    type: string
                  createdAt:
                    description: Stream creation
                    type: string
                  description:
                    description: Stream description
                    type: string
                  id:
                    type: string
                  indexingEnabled:
                    description: Enable ES indexing
                    type: boolean
                  indexingMaxSize:
                    description: Maximum indexing size (in GB)
                    format: int64
                    type: integer
                  indexingNotifyEnabled:
                    description: If set, notify when size is near 80, 90 or 100 %
                      of the maximum configured setting
                    type: boolean
                  isEditable:
                    description: Indicates if you are allowed to edit entry
                    type: boolean
                  isShareable:
                    description: Indicates if you are allowed to share entry
                    type: boolean
                  nbAlertCondition:
                    description: Number of alert condition
                    format: int64
                    type: integer
                  nbArchive:
                    description: Number of coldstored archives
                    format: int64
                    type: integer
                  parentStreamID:
                    description: Parent stream ID
                    type: string
                  pauseIndexingOnMaxSize:
                    description: If set, pause indexing when maximum size is reach
                    type: boolean
                  retentionID:
                    description: Retention ID
                    type: string
                  serviceName:
                    description: The service name
                    type: string
                  streamID:
                    description: Stream ID
                    type: string
                  title:
                    description: Stream description
                    type: string
                  updatedAt:
                    description: Stream last update
                    type: string
                  webSocketEnabled:
                    description: Enable Websocket
                    type: boolean
                required:
                - description
                - serviceName
                - title
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
