apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ovh.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: zones.domain.ovh.kubeform.com
spec:
  group: domain.ovh.kubeform.com
  names:
    kind: Zone
    listKind: ZoneList
    plural: zones
    singular: zone
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  dnssecSupported:
                    description: Is DNSSEC supported by this zone
                    type: boolean
                  hasDNSAnycast:
                    description: hasDnsAnycast flag of the DNS zone
                    type: boolean
                  id:
                    type: string
                  lastUpdate:
                    description: Last update date of the DNS zone
                    type: string
                  name:
                    description: Zone name
                    type: string
                  nameServers:
                    description: Name servers that host the DNS zone
                    items:
                      type: string
                    type: array
                  order:
                    description: Details about an Order
                    items:
                      properties:
                        date:
                          description: date
                          type: string
                        details:
                          description: Information about a Bill entry
                          items:
                            properties:
                              description:
                                description: description
                                type: string
                              domain:
                                description: expiration date
                                type: string
                              orderDetailID:
                                description: order detail id
                                format: int64
                                type: integer
                              quantity:
                                description: quantity
                                type: string
                            type: object
                          type: array
                        expirationDate:
                          description: expiration date
                          type: string
                        orderID:
                          description: order id
                          format: int64
                          type: integer
                      type: object
                    type: array
                  ovhSubsidiary:
                    description: Ovh Subsidiary
                    type: string
                  paymentMean:
                    description: Ovh payment mode
                    type: string
                  plan:
                    description: Product Plan to order
                    properties:
                      catalogName:
                        description: Catalog name
                        type: string
                      configuration:
                        description: Representation of a configuration item for personalizing
                          product
                        items:
                          properties:
                            label:
                              description: Identifier of the resource
                              type: string
                            value:
                              description: Path to the resource in API.OVH.COM
                              type: string
                          required:
                          - label
                          - value
                          type: object
                        type: array
                      duration:
                        description: duration
                        type: string
                      planCode:
                        description: Plan code
                        type: string
                      pricingMode:
                        description: Pricing model identifier
                        type: string
                    required:
                    - duration
                    - planCode
                    - pricingMode
                    type: object
                  planOption:
                    description: Product Plan to order
                    items:
                      properties:
                        catalogName:
                          description: Catalog name
                          type: string
                        configuration:
                          description: Representation of a configuration item for
                            personalizing product
                          items:
                            properties:
                              label:
                                description: Identifier of the resource
                                type: string
                              value:
                                description: Path to the resource in API.OVH.COM
                                type: string
                            required:
                            - label
                            - value
                            type: object
                          type: array
                        duration:
                          description: duration
                          type: string
                        planCode:
                          description: Plan code
                          type: string
                        pricingMode:
                          description: Pricing model identifier
                          type: string
                      required:
                      - duration
                      - planCode
                      - pricingMode
                      type: object
                    type: array
                required:
                - ovhSubsidiary
                - paymentMean
                - plan
                type: object
              state:
                properties:
                  dnssecSupported:
                    description: Is DNSSEC supported by this zone
                    type: boolean
                  hasDNSAnycast:
                    description: hasDnsAnycast flag of the DNS zone
                    type: boolean
                  id:
                    type: string
                  lastUpdate:
                    description: Last update date of the DNS zone
                    type: string
                  name:
                    description: Zone name
                    type: string
                  nameServers:
                    description: Name servers that host the DNS zone
                    items:
                      type: string
                    type: array
                  order:
                    description: Details about an Order
                    items:
                      properties:
                        date:
                          description: date
                          type: string
                        details:
                          description: Information about a Bill entry
                          items:
                            properties:
                              description:
                                description: description
                                type: string
                              domain:
                                description: expiration date
                                type: string
                              orderDetailID:
                                description: order detail id
                                format: int64
                                type: integer
                              quantity:
                                description: quantity
                                type: string
                            type: object
                          type: array
                        expirationDate:
                          description: expiration date
                          type: string
                        orderID:
                          description: order id
                          format: int64
                          type: integer
                      type: object
                    type: array
                  ovhSubsidiary:
                    description: Ovh Subsidiary
                    type: string
                  paymentMean:
                    description: Ovh payment mode
                    type: string
                  plan:
                    description: Product Plan to order
                    properties:
                      catalogName:
                        description: Catalog name
                        type: string
                      configuration:
                        description: Representation of a configuration item for personalizing
                          product
                        items:
                          properties:
                            label:
                              description: Identifier of the resource
                              type: string
                            value:
                              description: Path to the resource in API.OVH.COM
                              type: string
                          required:
                          - label
                          - value
                          type: object
                        type: array
                      duration:
                        description: duration
                        type: string
                      planCode:
                        description: Plan code
                        type: string
                      pricingMode:
                        description: Pricing model identifier
                        type: string
                    required:
                    - duration
                    - planCode
                    - pricingMode
                    type: object
                  planOption:
                    description: Product Plan to order
                    items:
                      properties:
                        catalogName:
                          description: Catalog name
                          type: string
                        configuration:
                          description: Representation of a configuration item for
                            personalizing product
                          items:
                            properties:
                              label:
                                description: Identifier of the resource
                                type: string
                              value:
                                description: Path to the resource in API.OVH.COM
                                type: string
                            required:
                            - label
                            - value
                            type: object
                          type: array
                        duration:
                          description: duration
                          type: string
                        planCode:
                          description: Plan code
                          type: string
                        pricingMode:
                          description: Pricing model identifier
                          type: string
                      required:
                      - duration
                      - planCode
                      - pricingMode
                      type: object
                    type: array
                required:
                - ovhSubsidiary
                - paymentMean
                - plan
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
