apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: ovh.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: installationtemplates.me.ovh.kubeform.com
spec:
  group: me.ovh.kubeform.com
  names:
    kind: InstallationTemplate
    listKind: InstallationTemplateList
    plural: installationtemplates
    singular: installationtemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  availableLanguages:
                    description: List of all language available for this template
                    items:
                      type: string
                    type: array
                  baseTemplateName:
                    description: OVH template name yours will be based on, choose
                      one among the list given by compatibleTemplates function
                    type: string
                  beta:
                    description: This distribution is new and, although tested and
                      functional, may still display odd behaviour
                    type: boolean
                  bitFormat:
                    description: This template bit format (32 or 64)
                    format: int64
                    type: integer
                  category:
                    description: Category of this template (informative only). (basic,
                      customer, hosting, other, readyToUse, virtualisation)
                    type: string
                  customization:
                    properties:
                      changeLog:
                        description: Template change log details Deprecated
                        type: string
                      customHostname:
                        description: Set up the server using the provided hostname
                          instead of the default hostname
                        type: string
                      postInstallationScriptLink:
                        description: Indicate the URL where your postinstall customisation
                          script is located
                        type: string
                      postInstallationScriptReturn:
                        description: 'indicate the string returned by your postinstall
                          customisation script on successful execution. Advice: your
                          script should return a unique validation string in case
                          of succes. A good example is ''loh1Xee7eo OK OK OK UGh8Ang1Gu'''
                        type: string
                      rating:
                        description: Deprecated
                        format: int64
                        type: integer
                      sshKeyName:
                        description: Name of the ssh key that should be installed.
                          Password login will be disabled
                        type: string
                      useDistributionKernel:
                        description: Use the distribution's native kernel instead
                          of the recommended OVH Kernel
                        type: boolean
                    type: object
                  defaultLanguage:
                    description: The default language of this template
                    type: string
                  deprecated:
                    description: is this distribution deprecated
                    type: boolean
                  description:
                    description: information about this template
                    type: string
                  distribution:
                    description: the distribution this template is based on
                    type: string
                  family:
                    description: this template family type (bsd,linux,solaris,windows)
                    type: string
                  filesystems:
                    description: Filesystems available (btrfs,ext3,ext4,ntfs,reiserfs,swap,ufs,xfs,zfs)
                    items:
                      type: string
                    type: array
                  hardRaidConfiguration:
                    description: This distribution supports hardware raid configuration
                      through the OVH API
                    type: boolean
                  id:
                    type: string
                  lastModification:
                    description: Date of last modification of the base image
                    type: string
                  lvmReady:
                    description: This distribution supports Logical Volumes (Linux
                      LVM)
                    type: boolean
                  removeDefaultPartitionSchemes:
                    description: Remove default partition schemes at creation
                    type: boolean
                  supportsDistributionKernel:
                    description: This distribution supports installation using the
                      distribution's native kernel instead of the recommended OVH
                      kernel
                    type: boolean
                  supportsGptLabel:
                    description: This distribution supports the GUID Partition Table
                      (GPT), providing up to 128 partitions that can have more than
                      2TB
                    type: boolean
                  supportsRtm:
                    description: This distribution supports RTM software
                    type: boolean
                  supportsSQLServer:
                    description: This distribution supports the microsoft SQL server
                    type: boolean
                  supportsUefi:
                    description: This distribution supports UEFI setup (no,only,yes)
                    type: string
                  templateName:
                    description: This template name
                    type: string
                required:
                - baseTemplateName
                - defaultLanguage
                - templateName
                type: object
              state:
                properties:
                  availableLanguages:
                    description: List of all language available for this template
                    items:
                      type: string
                    type: array
                  baseTemplateName:
                    description: OVH template name yours will be based on, choose
                      one among the list given by compatibleTemplates function
                    type: string
                  beta:
                    description: This distribution is new and, although tested and
                      functional, may still display odd behaviour
                    type: boolean
                  bitFormat:
                    description: This template bit format (32 or 64)
                    format: int64
                    type: integer
                  category:
                    description: Category of this template (informative only). (basic,
                      customer, hosting, other, readyToUse, virtualisation)
                    type: string
                  customization:
                    properties:
                      changeLog:
                        description: Template change log details Deprecated
                        type: string
                      customHostname:
                        description: Set up the server using the provided hostname
                          instead of the default hostname
                        type: string
                      postInstallationScriptLink:
                        description: Indicate the URL where your postinstall customisation
                          script is located
                        type: string
                      postInstallationScriptReturn:
                        description: 'indicate the string returned by your postinstall
                          customisation script on successful execution. Advice: your
                          script should return a unique validation string in case
                          of succes. A good example is ''loh1Xee7eo OK OK OK UGh8Ang1Gu'''
                        type: string
                      rating:
                        description: Deprecated
                        format: int64
                        type: integer
                      sshKeyName:
                        description: Name of the ssh key that should be installed.
                          Password login will be disabled
                        type: string
                      useDistributionKernel:
                        description: Use the distribution's native kernel instead
                          of the recommended OVH Kernel
                        type: boolean
                    type: object
                  defaultLanguage:
                    description: The default language of this template
                    type: string
                  deprecated:
                    description: is this distribution deprecated
                    type: boolean
                  description:
                    description: information about this template
                    type: string
                  distribution:
                    description: the distribution this template is based on
                    type: string
                  family:
                    description: this template family type (bsd,linux,solaris,windows)
                    type: string
                  filesystems:
                    description: Filesystems available (btrfs,ext3,ext4,ntfs,reiserfs,swap,ufs,xfs,zfs)
                    items:
                      type: string
                    type: array
                  hardRaidConfiguration:
                    description: This distribution supports hardware raid configuration
                      through the OVH API
                    type: boolean
                  id:
                    type: string
                  lastModification:
                    description: Date of last modification of the base image
                    type: string
                  lvmReady:
                    description: This distribution supports Logical Volumes (Linux
                      LVM)
                    type: boolean
                  removeDefaultPartitionSchemes:
                    description: Remove default partition schemes at creation
                    type: boolean
                  supportsDistributionKernel:
                    description: This distribution supports installation using the
                      distribution's native kernel instead of the recommended OVH
                      kernel
                    type: boolean
                  supportsGptLabel:
                    description: This distribution supports the GUID Partition Table
                      (GPT), providing up to 128 partitions that can have more than
                      2TB
                    type: boolean
                  supportsRtm:
                    description: This distribution supports RTM software
                    type: boolean
                  supportsSQLServer:
                    description: This distribution supports the microsoft SQL server
                    type: boolean
                  supportsUefi:
                    description: This distribution supports UEFI setup (no,only,yes)
                    type: string
                  templateName:
                    description: This template name
                    type: string
                required:
                - baseTemplateName
                - defaultLanguage
                - templateName
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
