/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	dbaasv1alpha1 "kubeform.dev/provider-ovh-api/apis/dbaas/v1alpha1"
	versioned "kubeform.dev/provider-ovh-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-ovh-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-ovh-api/client/listers/dbaas/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LogsOutputGraylogStreamInformer provides access to a shared informer and lister for
// LogsOutputGraylogStreams.
type LogsOutputGraylogStreamInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LogsOutputGraylogStreamLister
}

type logsOutputGraylogStreamInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLogsOutputGraylogStreamInformer constructs a new informer for LogsOutputGraylogStream type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLogsOutputGraylogStreamInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLogsOutputGraylogStreamInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLogsOutputGraylogStreamInformer constructs a new informer for LogsOutputGraylogStream type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLogsOutputGraylogStreamInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DbaasV1alpha1().LogsOutputGraylogStreams(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DbaasV1alpha1().LogsOutputGraylogStreams(namespace).Watch(context.TODO(), options)
			},
		},
		&dbaasv1alpha1.LogsOutputGraylogStream{},
		resyncPeriod,
		indexers,
	)
}

func (f *logsOutputGraylogStreamInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLogsOutputGraylogStreamInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *logsOutputGraylogStreamInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dbaasv1alpha1.LogsOutputGraylogStream{}, f.defaultInformer)
}

func (f *logsOutputGraylogStreamInformer) Lister() v1alpha1.LogsOutputGraylogStreamLister {
	return v1alpha1.NewLogsOutputGraylogStreamLister(f.Informer().GetIndexer())
}
