/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IdentityUserListerExpansion allows custom methods to be added to
// IdentityUserLister.
type IdentityUserListerExpansion interface{}

// IdentityUserNamespaceListerExpansion allows custom methods to be added to
// IdentityUserNamespaceLister.
type IdentityUserNamespaceListerExpansion interface{}

// InstallationTemplateListerExpansion allows custom methods to be added to
// InstallationTemplateLister.
type InstallationTemplateListerExpansion interface{}

// InstallationTemplateNamespaceListerExpansion allows custom methods to be added to
// InstallationTemplateNamespaceLister.
type InstallationTemplateNamespaceListerExpansion interface{}

// InstallationTemplatePartitionSchemeListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemeLister.
type InstallationTemplatePartitionSchemeListerExpansion interface{}

// InstallationTemplatePartitionSchemeNamespaceListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemeNamespaceLister.
type InstallationTemplatePartitionSchemeNamespaceListerExpansion interface{}

// InstallationTemplatePartitionSchemeHardwareRaidListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemeHardwareRaidLister.
type InstallationTemplatePartitionSchemeHardwareRaidListerExpansion interface{}

// InstallationTemplatePartitionSchemeHardwareRaidNamespaceListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemeHardwareRaidNamespaceLister.
type InstallationTemplatePartitionSchemeHardwareRaidNamespaceListerExpansion interface{}

// InstallationTemplatePartitionSchemePartitionListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemePartitionLister.
type InstallationTemplatePartitionSchemePartitionListerExpansion interface{}

// InstallationTemplatePartitionSchemePartitionNamespaceListerExpansion allows custom methods to be added to
// InstallationTemplatePartitionSchemePartitionNamespaceLister.
type InstallationTemplatePartitionSchemePartitionNamespaceListerExpansion interface{}

// IpxeScriptListerExpansion allows custom methods to be added to
// IpxeScriptLister.
type IpxeScriptListerExpansion interface{}

// IpxeScriptNamespaceListerExpansion allows custom methods to be added to
// IpxeScriptNamespaceLister.
type IpxeScriptNamespaceListerExpansion interface{}

// SshKeyListerExpansion allows custom methods to be added to
// SshKeyLister.
type SshKeyListerExpansion interface{}

// SshKeyNamespaceListerExpansion allows custom methods to be added to
// SshKeyNamespaceLister.
type SshKeyNamespaceListerExpansion interface{}
