/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubeform.dev/provider-ovh-api/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// HttpFarms returns a HttpFarmInformer.
	HttpFarms() HttpFarmInformer
	// HttpFarmServers returns a HttpFarmServerInformer.
	HttpFarmServers() HttpFarmServerInformer
	// HttpFrontends returns a HttpFrontendInformer.
	HttpFrontends() HttpFrontendInformer
	// HttpRoutes returns a HttpRouteInformer.
	HttpRoutes() HttpRouteInformer
	// HttpRouteRules returns a HttpRouteRuleInformer.
	HttpRouteRules() HttpRouteRuleInformer
	// Iploadbalancings returns a IploadbalancingInformer.
	Iploadbalancings() IploadbalancingInformer
	// Refreshes returns a RefreshInformer.
	Refreshes() RefreshInformer
	// TcpFarms returns a TcpFarmInformer.
	TcpFarms() TcpFarmInformer
	// TcpFarmServers returns a TcpFarmServerInformer.
	TcpFarmServers() TcpFarmServerInformer
	// TcpFrontends returns a TcpFrontendInformer.
	TcpFrontends() TcpFrontendInformer
	// TcpRoutes returns a TcpRouteInformer.
	TcpRoutes() TcpRouteInformer
	// TcpRouteRules returns a TcpRouteRuleInformer.
	TcpRouteRules() TcpRouteRuleInformer
	// VrackNetworks returns a VrackNetworkInformer.
	VrackNetworks() VrackNetworkInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// HttpFarms returns a HttpFarmInformer.
func (v *version) HttpFarms() HttpFarmInformer {
	return &httpFarmInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HttpFarmServers returns a HttpFarmServerInformer.
func (v *version) HttpFarmServers() HttpFarmServerInformer {
	return &httpFarmServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HttpFrontends returns a HttpFrontendInformer.
func (v *version) HttpFrontends() HttpFrontendInformer {
	return &httpFrontendInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HttpRoutes returns a HttpRouteInformer.
func (v *version) HttpRoutes() HttpRouteInformer {
	return &httpRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HttpRouteRules returns a HttpRouteRuleInformer.
func (v *version) HttpRouteRules() HttpRouteRuleInformer {
	return &httpRouteRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Iploadbalancings returns a IploadbalancingInformer.
func (v *version) Iploadbalancings() IploadbalancingInformer {
	return &iploadbalancingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Refreshes returns a RefreshInformer.
func (v *version) Refreshes() RefreshInformer {
	return &refreshInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcpFarms returns a TcpFarmInformer.
func (v *version) TcpFarms() TcpFarmInformer {
	return &tcpFarmInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcpFarmServers returns a TcpFarmServerInformer.
func (v *version) TcpFarmServers() TcpFarmServerInformer {
	return &tcpFarmServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcpFrontends returns a TcpFrontendInformer.
func (v *version) TcpFrontends() TcpFrontendInformer {
	return &tcpFrontendInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcpRoutes returns a TcpRouteInformer.
func (v *version) TcpRoutes() TcpRouteInformer {
	return &tcpRouteInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// TcpRouteRules returns a TcpRouteRuleInformer.
func (v *version) TcpRouteRules() TcpRouteRuleInformer {
	return &tcpRouteRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VrackNetworks returns a VrackNetworkInformer.
func (v *version) VrackNetworks() VrackNetworkInformer {
	return &vrackNetworkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
