/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/domain/v1alpha1"
	scheme "kubeform.dev/provider-ovh-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ZoneRedirectionsGetter has a method to return a ZoneRedirectionInterface.
// A group's client should implement this interface.
type ZoneRedirectionsGetter interface {
	ZoneRedirections(namespace string) ZoneRedirectionInterface
}

// ZoneRedirectionInterface has methods to work with ZoneRedirection resources.
type ZoneRedirectionInterface interface {
	Create(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.CreateOptions) (*v1alpha1.ZoneRedirection, error)
	Update(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.UpdateOptions) (*v1alpha1.ZoneRedirection, error)
	UpdateStatus(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.UpdateOptions) (*v1alpha1.ZoneRedirection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ZoneRedirection, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ZoneRedirectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZoneRedirection, err error)
	ZoneRedirectionExpansion
}

// zoneRedirections implements ZoneRedirectionInterface
type zoneRedirections struct {
	client rest.Interface
	ns     string
}

// newZoneRedirections returns a ZoneRedirections
func newZoneRedirections(c *DomainV1alpha1Client, namespace string) *zoneRedirections {
	return &zoneRedirections{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the zoneRedirection, and returns the corresponding zoneRedirection object, and an error if there is any.
func (c *zoneRedirections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ZoneRedirection, err error) {
	result = &v1alpha1.ZoneRedirection{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zoneredirections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ZoneRedirections that match those selectors.
func (c *zoneRedirections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ZoneRedirectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ZoneRedirectionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("zoneredirections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested zoneRedirections.
func (c *zoneRedirections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("zoneredirections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a zoneRedirection and creates it.  Returns the server's representation of the zoneRedirection, and an error, if there is any.
func (c *zoneRedirections) Create(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.CreateOptions) (result *v1alpha1.ZoneRedirection, err error) {
	result = &v1alpha1.ZoneRedirection{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("zoneredirections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zoneRedirection).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a zoneRedirection and updates it. Returns the server's representation of the zoneRedirection, and an error, if there is any.
func (c *zoneRedirections) Update(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.UpdateOptions) (result *v1alpha1.ZoneRedirection, err error) {
	result = &v1alpha1.ZoneRedirection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zoneredirections").
		Name(zoneRedirection.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zoneRedirection).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *zoneRedirections) UpdateStatus(ctx context.Context, zoneRedirection *v1alpha1.ZoneRedirection, opts v1.UpdateOptions) (result *v1alpha1.ZoneRedirection, err error) {
	result = &v1alpha1.ZoneRedirection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("zoneredirections").
		Name(zoneRedirection.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(zoneRedirection).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the zoneRedirection and deletes it. Returns an error if one occurs.
func (c *zoneRedirections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zoneredirections").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *zoneRedirections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("zoneredirections").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched zoneRedirection.
func (c *zoneRedirections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZoneRedirection, err error) {
	result = &v1alpha1.ZoneRedirection{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("zoneredirections").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
