/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVrackNetworks implements VrackNetworkInterface
type FakeVrackNetworks struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var vracknetworksResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "vracknetworks"}

var vracknetworksKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "VrackNetwork"}

// Get takes name of the vrackNetwork, and returns the corresponding vrackNetwork object, and an error if there is any.
func (c *FakeVrackNetworks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VrackNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vracknetworksResource, c.ns, name), &v1alpha1.VrackNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VrackNetwork), err
}

// List takes label and field selectors, and returns the list of VrackNetworks that match those selectors.
func (c *FakeVrackNetworks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VrackNetworkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vracknetworksResource, vracknetworksKind, c.ns, opts), &v1alpha1.VrackNetworkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VrackNetworkList{ListMeta: obj.(*v1alpha1.VrackNetworkList).ListMeta}
	for _, item := range obj.(*v1alpha1.VrackNetworkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vrackNetworks.
func (c *FakeVrackNetworks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vracknetworksResource, c.ns, opts))

}

// Create takes the representation of a vrackNetwork and creates it.  Returns the server's representation of the vrackNetwork, and an error, if there is any.
func (c *FakeVrackNetworks) Create(ctx context.Context, vrackNetwork *v1alpha1.VrackNetwork, opts v1.CreateOptions) (result *v1alpha1.VrackNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vracknetworksResource, c.ns, vrackNetwork), &v1alpha1.VrackNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VrackNetwork), err
}

// Update takes the representation of a vrackNetwork and updates it. Returns the server's representation of the vrackNetwork, and an error, if there is any.
func (c *FakeVrackNetworks) Update(ctx context.Context, vrackNetwork *v1alpha1.VrackNetwork, opts v1.UpdateOptions) (result *v1alpha1.VrackNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vracknetworksResource, c.ns, vrackNetwork), &v1alpha1.VrackNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VrackNetwork), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVrackNetworks) UpdateStatus(ctx context.Context, vrackNetwork *v1alpha1.VrackNetwork, opts v1.UpdateOptions) (*v1alpha1.VrackNetwork, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vracknetworksResource, "status", c.ns, vrackNetwork), &v1alpha1.VrackNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VrackNetwork), err
}

// Delete takes name of the vrackNetwork and deletes it. Returns an error if one occurs.
func (c *FakeVrackNetworks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vracknetworksResource, c.ns, name), &v1alpha1.VrackNetwork{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVrackNetworks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vracknetworksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VrackNetworkList{})
	return err
}

// Patch applies the patch and returns the patched vrackNetwork.
func (c *FakeVrackNetworks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VrackNetwork, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vracknetworksResource, c.ns, name, pt, data, subresources...), &v1alpha1.VrackNetwork{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VrackNetwork), err
}
