/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHttpRoutes implements HttpRouteInterface
type FakeHttpRoutes struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var httproutesResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "httproutes"}

var httproutesKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "HttpRoute"}

// Get takes name of the httpRoute, and returns the corresponding httpRoute object, and an error if there is any.
func (c *FakeHttpRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HttpRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httproutesResource, c.ns, name), &v1alpha1.HttpRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRoute), err
}

// List takes label and field selectors, and returns the list of HttpRoutes that match those selectors.
func (c *FakeHttpRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HttpRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httproutesResource, httproutesKind, c.ns, opts), &v1alpha1.HttpRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HttpRouteList{ListMeta: obj.(*v1alpha1.HttpRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.HttpRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested httpRoutes.
func (c *FakeHttpRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httproutesResource, c.ns, opts))

}

// Create takes the representation of a httpRoute and creates it.  Returns the server's representation of the httpRoute, and an error, if there is any.
func (c *FakeHttpRoutes) Create(ctx context.Context, httpRoute *v1alpha1.HttpRoute, opts v1.CreateOptions) (result *v1alpha1.HttpRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httproutesResource, c.ns, httpRoute), &v1alpha1.HttpRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRoute), err
}

// Update takes the representation of a httpRoute and updates it. Returns the server's representation of the httpRoute, and an error, if there is any.
func (c *FakeHttpRoutes) Update(ctx context.Context, httpRoute *v1alpha1.HttpRoute, opts v1.UpdateOptions) (result *v1alpha1.HttpRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httproutesResource, c.ns, httpRoute), &v1alpha1.HttpRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHttpRoutes) UpdateStatus(ctx context.Context, httpRoute *v1alpha1.HttpRoute, opts v1.UpdateOptions) (*v1alpha1.HttpRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httproutesResource, "status", c.ns, httpRoute), &v1alpha1.HttpRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRoute), err
}

// Delete takes name of the httpRoute and deletes it. Returns an error if one occurs.
func (c *FakeHttpRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httproutesResource, c.ns, name), &v1alpha1.HttpRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHttpRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httproutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HttpRouteList{})
	return err
}

// Patch applies the patch and returns the patched httpRoute.
func (c *FakeHttpRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httproutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HttpRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRoute), err
}
