/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHttpFarmServers implements HttpFarmServerInterface
type FakeHttpFarmServers struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var httpfarmserversResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "httpfarmservers"}

var httpfarmserversKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "HttpFarmServer"}

// Get takes name of the httpFarmServer, and returns the corresponding httpFarmServer object, and an error if there is any.
func (c *FakeHttpFarmServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HttpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httpfarmserversResource, c.ns, name), &v1alpha1.HttpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarmServer), err
}

// List takes label and field selectors, and returns the list of HttpFarmServers that match those selectors.
func (c *FakeHttpFarmServers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HttpFarmServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httpfarmserversResource, httpfarmserversKind, c.ns, opts), &v1alpha1.HttpFarmServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HttpFarmServerList{ListMeta: obj.(*v1alpha1.HttpFarmServerList).ListMeta}
	for _, item := range obj.(*v1alpha1.HttpFarmServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested httpFarmServers.
func (c *FakeHttpFarmServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httpfarmserversResource, c.ns, opts))

}

// Create takes the representation of a httpFarmServer and creates it.  Returns the server's representation of the httpFarmServer, and an error, if there is any.
func (c *FakeHttpFarmServers) Create(ctx context.Context, httpFarmServer *v1alpha1.HttpFarmServer, opts v1.CreateOptions) (result *v1alpha1.HttpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httpfarmserversResource, c.ns, httpFarmServer), &v1alpha1.HttpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarmServer), err
}

// Update takes the representation of a httpFarmServer and updates it. Returns the server's representation of the httpFarmServer, and an error, if there is any.
func (c *FakeHttpFarmServers) Update(ctx context.Context, httpFarmServer *v1alpha1.HttpFarmServer, opts v1.UpdateOptions) (result *v1alpha1.HttpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httpfarmserversResource, c.ns, httpFarmServer), &v1alpha1.HttpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarmServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHttpFarmServers) UpdateStatus(ctx context.Context, httpFarmServer *v1alpha1.HttpFarmServer, opts v1.UpdateOptions) (*v1alpha1.HttpFarmServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httpfarmserversResource, "status", c.ns, httpFarmServer), &v1alpha1.HttpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarmServer), err
}

// Delete takes name of the httpFarmServer and deletes it. Returns an error if one occurs.
func (c *FakeHttpFarmServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httpfarmserversResource, c.ns, name), &v1alpha1.HttpFarmServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHttpFarmServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httpfarmserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HttpFarmServerList{})
	return err
}

// Patch applies the patch and returns the patched httpFarmServer.
func (c *FakeHttpFarmServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httpfarmserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.HttpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarmServer), err
}
