/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHttpFarms implements HttpFarmInterface
type FakeHttpFarms struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var httpfarmsResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "httpfarms"}

var httpfarmsKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "HttpFarm"}

// Get takes name of the httpFarm, and returns the corresponding httpFarm object, and an error if there is any.
func (c *FakeHttpFarms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HttpFarm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httpfarmsResource, c.ns, name), &v1alpha1.HttpFarm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarm), err
}

// List takes label and field selectors, and returns the list of HttpFarms that match those selectors.
func (c *FakeHttpFarms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HttpFarmList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httpfarmsResource, httpfarmsKind, c.ns, opts), &v1alpha1.HttpFarmList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HttpFarmList{ListMeta: obj.(*v1alpha1.HttpFarmList).ListMeta}
	for _, item := range obj.(*v1alpha1.HttpFarmList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested httpFarms.
func (c *FakeHttpFarms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httpfarmsResource, c.ns, opts))

}

// Create takes the representation of a httpFarm and creates it.  Returns the server's representation of the httpFarm, and an error, if there is any.
func (c *FakeHttpFarms) Create(ctx context.Context, httpFarm *v1alpha1.HttpFarm, opts v1.CreateOptions) (result *v1alpha1.HttpFarm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httpfarmsResource, c.ns, httpFarm), &v1alpha1.HttpFarm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarm), err
}

// Update takes the representation of a httpFarm and updates it. Returns the server's representation of the httpFarm, and an error, if there is any.
func (c *FakeHttpFarms) Update(ctx context.Context, httpFarm *v1alpha1.HttpFarm, opts v1.UpdateOptions) (result *v1alpha1.HttpFarm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httpfarmsResource, c.ns, httpFarm), &v1alpha1.HttpFarm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarm), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHttpFarms) UpdateStatus(ctx context.Context, httpFarm *v1alpha1.HttpFarm, opts v1.UpdateOptions) (*v1alpha1.HttpFarm, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httpfarmsResource, "status", c.ns, httpFarm), &v1alpha1.HttpFarm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarm), err
}

// Delete takes name of the httpFarm and deletes it. Returns an error if one occurs.
func (c *FakeHttpFarms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httpfarmsResource, c.ns, name), &v1alpha1.HttpFarm{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHttpFarms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httpfarmsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HttpFarmList{})
	return err
}

// Patch applies the patch and returns the patched httpFarm.
func (c *FakeHttpFarms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpFarm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httpfarmsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HttpFarm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpFarm), err
}
