/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubeform.dev/provider-ovh-api/client/clientset/versioned/typed/iploadbalancing/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIploadbalancingV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIploadbalancingV1alpha1) HttpFarms(namespace string) v1alpha1.HttpFarmInterface {
	return &FakeHttpFarms{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) HttpFarmServers(namespace string) v1alpha1.HttpFarmServerInterface {
	return &FakeHttpFarmServers{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) HttpFrontends(namespace string) v1alpha1.HttpFrontendInterface {
	return &FakeHttpFrontends{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) HttpRoutes(namespace string) v1alpha1.HttpRouteInterface {
	return &FakeHttpRoutes{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) HttpRouteRules(namespace string) v1alpha1.HttpRouteRuleInterface {
	return &FakeHttpRouteRules{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) Iploadbalancings(namespace string) v1alpha1.IploadbalancingInterface {
	return &FakeIploadbalancings{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) Refreshes(namespace string) v1alpha1.RefreshInterface {
	return &FakeRefreshes{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) TcpFarms(namespace string) v1alpha1.TcpFarmInterface {
	return &FakeTcpFarms{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) TcpFarmServers(namespace string) v1alpha1.TcpFarmServerInterface {
	return &FakeTcpFarmServers{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) TcpFrontends(namespace string) v1alpha1.TcpFrontendInterface {
	return &FakeTcpFrontends{c, namespace}
}

func (c *FakeIploadbalancingV1alpha1) VrackNetworks(namespace string) v1alpha1.VrackNetworkInterface {
	return &FakeVrackNetworks{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIploadbalancingV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
