/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHttpRouteRules implements HttpRouteRuleInterface
type FakeHttpRouteRules struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var httprouterulesResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "httprouterules"}

var httprouterulesKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "HttpRouteRule"}

// Get takes name of the httpRouteRule, and returns the corresponding httpRouteRule object, and an error if there is any.
func (c *FakeHttpRouteRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HttpRouteRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httprouterulesResource, c.ns, name), &v1alpha1.HttpRouteRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRouteRule), err
}

// List takes label and field selectors, and returns the list of HttpRouteRules that match those selectors.
func (c *FakeHttpRouteRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HttpRouteRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httprouterulesResource, httprouterulesKind, c.ns, opts), &v1alpha1.HttpRouteRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HttpRouteRuleList{ListMeta: obj.(*v1alpha1.HttpRouteRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.HttpRouteRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested httpRouteRules.
func (c *FakeHttpRouteRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httprouterulesResource, c.ns, opts))

}

// Create takes the representation of a httpRouteRule and creates it.  Returns the server's representation of the httpRouteRule, and an error, if there is any.
func (c *FakeHttpRouteRules) Create(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.CreateOptions) (result *v1alpha1.HttpRouteRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httprouterulesResource, c.ns, httpRouteRule), &v1alpha1.HttpRouteRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRouteRule), err
}

// Update takes the representation of a httpRouteRule and updates it. Returns the server's representation of the httpRouteRule, and an error, if there is any.
func (c *FakeHttpRouteRules) Update(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (result *v1alpha1.HttpRouteRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httprouterulesResource, c.ns, httpRouteRule), &v1alpha1.HttpRouteRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRouteRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHttpRouteRules) UpdateStatus(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (*v1alpha1.HttpRouteRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httprouterulesResource, "status", c.ns, httpRouteRule), &v1alpha1.HttpRouteRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRouteRule), err
}

// Delete takes name of the httpRouteRule and deletes it. Returns an error if one occurs.
func (c *FakeHttpRouteRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(httprouterulesResource, c.ns, name), &v1alpha1.HttpRouteRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHttpRouteRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httprouterulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HttpRouteRuleList{})
	return err
}

// Patch applies the patch and returns the patched httpRouteRule.
func (c *FakeHttpRouteRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpRouteRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httprouterulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HttpRouteRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HttpRouteRule), err
}
