/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTcpFarmServers implements TcpFarmServerInterface
type FakeTcpFarmServers struct {
	Fake *FakeIploadbalancingV1alpha1
	ns   string
}

var tcpfarmserversResource = schema.GroupVersionResource{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Resource: "tcpfarmservers"}

var tcpfarmserversKind = schema.GroupVersionKind{Group: "iploadbalancing.ovh.kubeform.com", Version: "v1alpha1", Kind: "TcpFarmServer"}

// Get takes name of the tcpFarmServer, and returns the corresponding tcpFarmServer object, and an error if there is any.
func (c *FakeTcpFarmServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TcpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tcpfarmserversResource, c.ns, name), &v1alpha1.TcpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TcpFarmServer), err
}

// List takes label and field selectors, and returns the list of TcpFarmServers that match those selectors.
func (c *FakeTcpFarmServers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TcpFarmServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tcpfarmserversResource, tcpfarmserversKind, c.ns, opts), &v1alpha1.TcpFarmServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TcpFarmServerList{ListMeta: obj.(*v1alpha1.TcpFarmServerList).ListMeta}
	for _, item := range obj.(*v1alpha1.TcpFarmServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tcpFarmServers.
func (c *FakeTcpFarmServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tcpfarmserversResource, c.ns, opts))

}

// Create takes the representation of a tcpFarmServer and creates it.  Returns the server's representation of the tcpFarmServer, and an error, if there is any.
func (c *FakeTcpFarmServers) Create(ctx context.Context, tcpFarmServer *v1alpha1.TcpFarmServer, opts v1.CreateOptions) (result *v1alpha1.TcpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tcpfarmserversResource, c.ns, tcpFarmServer), &v1alpha1.TcpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TcpFarmServer), err
}

// Update takes the representation of a tcpFarmServer and updates it. Returns the server's representation of the tcpFarmServer, and an error, if there is any.
func (c *FakeTcpFarmServers) Update(ctx context.Context, tcpFarmServer *v1alpha1.TcpFarmServer, opts v1.UpdateOptions) (result *v1alpha1.TcpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tcpfarmserversResource, c.ns, tcpFarmServer), &v1alpha1.TcpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TcpFarmServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTcpFarmServers) UpdateStatus(ctx context.Context, tcpFarmServer *v1alpha1.TcpFarmServer, opts v1.UpdateOptions) (*v1alpha1.TcpFarmServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tcpfarmserversResource, "status", c.ns, tcpFarmServer), &v1alpha1.TcpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TcpFarmServer), err
}

// Delete takes name of the tcpFarmServer and deletes it. Returns an error if one occurs.
func (c *FakeTcpFarmServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tcpfarmserversResource, c.ns, name), &v1alpha1.TcpFarmServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTcpFarmServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tcpfarmserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TcpFarmServerList{})
	return err
}

// Patch applies the patch and returns the patched tcpFarmServer.
func (c *FakeTcpFarmServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TcpFarmServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tcpfarmserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.TcpFarmServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TcpFarmServer), err
}
