/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/iploadbalancing/v1alpha1"
	scheme "kubeform.dev/provider-ovh-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HttpRouteRulesGetter has a method to return a HttpRouteRuleInterface.
// A group's client should implement this interface.
type HttpRouteRulesGetter interface {
	HttpRouteRules(namespace string) HttpRouteRuleInterface
}

// HttpRouteRuleInterface has methods to work with HttpRouteRule resources.
type HttpRouteRuleInterface interface {
	Create(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.CreateOptions) (*v1alpha1.HttpRouteRule, error)
	Update(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (*v1alpha1.HttpRouteRule, error)
	UpdateStatus(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (*v1alpha1.HttpRouteRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HttpRouteRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HttpRouteRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpRouteRule, err error)
	HttpRouteRuleExpansion
}

// httpRouteRules implements HttpRouteRuleInterface
type httpRouteRules struct {
	client rest.Interface
	ns     string
}

// newHttpRouteRules returns a HttpRouteRules
func newHttpRouteRules(c *IploadbalancingV1alpha1Client, namespace string) *httpRouteRules {
	return &httpRouteRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the httpRouteRule, and returns the corresponding httpRouteRule object, and an error if there is any.
func (c *httpRouteRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HttpRouteRule, err error) {
	result = &v1alpha1.HttpRouteRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httprouterules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HttpRouteRules that match those selectors.
func (c *httpRouteRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HttpRouteRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HttpRouteRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("httprouterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested httpRouteRules.
func (c *httpRouteRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("httprouterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a httpRouteRule and creates it.  Returns the server's representation of the httpRouteRule, and an error, if there is any.
func (c *httpRouteRules) Create(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.CreateOptions) (result *v1alpha1.HttpRouteRule, err error) {
	result = &v1alpha1.HttpRouteRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("httprouterules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpRouteRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a httpRouteRule and updates it. Returns the server's representation of the httpRouteRule, and an error, if there is any.
func (c *httpRouteRules) Update(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (result *v1alpha1.HttpRouteRule, err error) {
	result = &v1alpha1.HttpRouteRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("httprouterules").
		Name(httpRouteRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpRouteRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *httpRouteRules) UpdateStatus(ctx context.Context, httpRouteRule *v1alpha1.HttpRouteRule, opts v1.UpdateOptions) (result *v1alpha1.HttpRouteRule, err error) {
	result = &v1alpha1.HttpRouteRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("httprouterules").
		Name(httpRouteRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(httpRouteRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the httpRouteRule and deletes it. Returns an error if one occurs.
func (c *httpRouteRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httprouterules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *httpRouteRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("httprouterules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched httpRouteRule.
func (c *httpRouteRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HttpRouteRule, err error) {
	result = &v1alpha1.HttpRouteRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("httprouterules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
