/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ovh-api/apis/domain/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeZoneRecords implements ZoneRecordInterface
type FakeZoneRecords struct {
	Fake *FakeDomainV1alpha1
	ns   string
}

var zonerecordsResource = schema.GroupVersionResource{Group: "domain.ovh.kubeform.com", Version: "v1alpha1", Resource: "zonerecords"}

var zonerecordsKind = schema.GroupVersionKind{Group: "domain.ovh.kubeform.com", Version: "v1alpha1", Kind: "ZoneRecord"}

// Get takes name of the zoneRecord, and returns the corresponding zoneRecord object, and an error if there is any.
func (c *FakeZoneRecords) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ZoneRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(zonerecordsResource, c.ns, name), &v1alpha1.ZoneRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZoneRecord), err
}

// List takes label and field selectors, and returns the list of ZoneRecords that match those selectors.
func (c *FakeZoneRecords) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ZoneRecordList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(zonerecordsResource, zonerecordsKind, c.ns, opts), &v1alpha1.ZoneRecordList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ZoneRecordList{ListMeta: obj.(*v1alpha1.ZoneRecordList).ListMeta}
	for _, item := range obj.(*v1alpha1.ZoneRecordList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested zoneRecords.
func (c *FakeZoneRecords) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(zonerecordsResource, c.ns, opts))

}

// Create takes the representation of a zoneRecord and creates it.  Returns the server's representation of the zoneRecord, and an error, if there is any.
func (c *FakeZoneRecords) Create(ctx context.Context, zoneRecord *v1alpha1.ZoneRecord, opts v1.CreateOptions) (result *v1alpha1.ZoneRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(zonerecordsResource, c.ns, zoneRecord), &v1alpha1.ZoneRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZoneRecord), err
}

// Update takes the representation of a zoneRecord and updates it. Returns the server's representation of the zoneRecord, and an error, if there is any.
func (c *FakeZoneRecords) Update(ctx context.Context, zoneRecord *v1alpha1.ZoneRecord, opts v1.UpdateOptions) (result *v1alpha1.ZoneRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(zonerecordsResource, c.ns, zoneRecord), &v1alpha1.ZoneRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZoneRecord), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeZoneRecords) UpdateStatus(ctx context.Context, zoneRecord *v1alpha1.ZoneRecord, opts v1.UpdateOptions) (*v1alpha1.ZoneRecord, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(zonerecordsResource, "status", c.ns, zoneRecord), &v1alpha1.ZoneRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZoneRecord), err
}

// Delete takes name of the zoneRecord and deletes it. Returns an error if one occurs.
func (c *FakeZoneRecords) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(zonerecordsResource, c.ns, name), &v1alpha1.ZoneRecord{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeZoneRecords) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(zonerecordsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ZoneRecordList{})
	return err
}

// Patch applies the patch and returns the patched zoneRecord.
func (c *FakeZoneRecords) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ZoneRecord, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(zonerecordsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ZoneRecord{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ZoneRecord), err
}
